---
apiVersion: v1
kind: Service
metadata:
    name: website
    namespace: services
    labels:
        app: backend
spec:
    type: LoadBalancer
    selector:
        app: backend
    ports:
    - port: 80
      protocol: TCP  
      targetPort: 80
